calc:
  epsilon: 1.0e-06
model:
  init_kernel_hyperparameter:
    alpha: 0.8
    eta1: 0.5
    eta2: 0.0
    l1: -1.5
    l2: -1.5
  kernel_form: product
  kernel_type: se
optimization:
  eps: 1.0e-05
  lr: 1.0e-05
  maxiter_GD: 400
  maxiter_scipy: 1
  method_GD: adam
  method_scipy: Nelder-Mead
plot:
  error_limit:
  - 0.0001
  - 0.1
  std_limit:
  - 0.0001
  - 0.1
  val_limits:
  - - 0.0
    - 1.3
  - - -0.14
    - 0.14
  - - 0.0
    - 1.0
  x_for_ux: 0.5
test_data:
  infer_p: 0
  test_num: 40
  ux_test: 0
training_data:
  condition:
    channel_length: 2.5
    channel_width: 1
    #epsilon: 0.4
    oscillation_amplitude: 0.2
    use_difp: False
    delta_p: -30
  generate_params:
    div_num: 44
    div_pad: 0.03
    f_num: 44
    f_pad: 0.03
    p_num: 48
    u_num: 48
    difp_num: 20
  num_training_points:
    divu: 356
    fx: 356
    fy: 356
    p: 1
    ux: 94
    uy: 94
lbls:
  train:
  - 'r' 
  - 'f'
  test:
  - 'r'
  - 'f'
  infer:
  - 'f'
  - 'std'
  record:
  - 'x'
  - 'fun'
  - 'norm_of_grads'
  analysis:
  - 'abs_error'
  - 'rel_error'
  - 'max_abs_error'
  - 'max_rel_error'
  - 'mean_abs_error'
  - 'mean_rel_error'
  kernel_arg:
  - 'uxux'
  - 'uyuy'
  - 'pp'
  - 'uxuy'
  - 'uxp'
  - 'uyp'
vnames:
  train:
  - 'ux'
  - 'uy'
  - 'p'
  - 'fx'
  - 'fy'
  - 'divu'
  test:
  - 'ux'
  - 'uy'
  - 'p'
  infer:
  - 'ux'
  - 'uy'
  - 'p'
  analysis:
  - 'ux'
  - 'uy'
  - 'p'
system_type: 'Stokes_2D'
