calc:
  epsilon: 1.0e-06
lbls:
  analysis:
  - abs_error
  - rel_error
  - max_abs_error
  - max_rel_error
  - mean_abs_error
  - mean_rel_error
  infer:
  - f
  - std
  kernel_arg:
  - uxux
  - uyuy
  - pp
  - uxuy
  - uxp
  - uyp
  record:
  - x
  - fun
  - norm_of_grads
  test:
  - r
  - f
  train:
  - r
  - f
model:
  add_noise: False
  init_kernel_hyperparameter:
    pp:
    - 0.8
    - -1.5
    - -1.5
    std_noise:
    - 0.01
    uxp:
    - 0.0
    - -1.5
    - -1.5
    uxux:
    - 0.8
    - -1.5
    - -1.5
    uxuy:
    - 0.0
    - -1.5
    - -1.5
    uyp:
    - 0.0
    - -1.5
    - -1.5
    uyuy:
    - 0.8
    - -1.5
    - -1.5
  kernel_form: product
  kernel_type: se
optimization:
  eps: 1.0e-05
  loss_ridge_regression: false
  lr: 1.0e-05
  maxiter_GD: 40
  maxiter_first: 10
  method_GD: adam
  method_first: Nelder-Mead
plot:
  error_limit:
  - 0.0001
  - 0.1
  std_limit:
  - 0.0001
  - 0.1
  val_limits:
  - - 0.0
    - 1.3
  - - -0.14
    - 0.14
  - - 0.0
    - 1.0
  x_for_ux: 0.5
system_type: Stokes_2D
test_data:
  infer_p: false
  test_num: 18
  use_fem_result: true
  use_spm_result: false
  ux_test: 0
training_data:
  condition:
    channel_length: 2.5
    channel_width: 1
    cut_last_x: false
    delta_p: -30
    infer_gradp: false
    infer_ux_wall: false
    noise_fraction: 0.0
    oscillation_amplitude: 0.2
    random_arrange: false
    use_1d_u: false
    use_difp: true
    use_difu: true
    use_force_as_constant_pressure: true
    use_gradp_training: false
    use_inlet_outlet_u: false
    use_noisy_ux: false
    use_only_bottom_u: false
    use_only_inlet_gradp: false
    use_random_u: false
  generate_params:
    difp_loc: inlet_outlet
    difp_num: 16
    difp_pad: 0.03
    difu_num: 16
    div_num: 44
    div_pad: 0.03
    f_num: 44
    f_pad: 0.03
    p_num: 0
    u_num: 44
  num_training_points:
    difp: 15
    difux: 15
    difuy: 15
    divu: 337
    fx: 337
    fy: 337
    ux: 62
    uy: 62
vnames:
  analysis:
  - ux
  - uy
  infer:
  - ux
  - uy
  test:
  - ux
  - uy
  train:
  - ux
  - uy
  - difux
  - difuy
  - fx
  - fy
  - divu
  - difp
