calc:
  epsilon: 1.0e-06
model:
  init_kernel_hyperparameter:
    alpha: 0.8
    eta1: 0.0
    eta2: 0.0
    l1: 0.0
    l2: 0.0
  kernel_form: additive
  kernel_type: se
  distance_func: False
optimization:
  eps: 1.0e-05
  lr: 1.0e-05
  maxiter_GD: 200
  maxiter_scipy: 1
  method_GD: adam
  method_scipy: Nelder-Mead
  loss_ridge_regression: False
  ridge_alpha: 1
plot:
  error_limit:
  - 0.0001
  - 0.1
  std_limit:
  - 0
  - 0.002
  val_limits:
  - - 0.0
    - 1.0
  - - -0.01
    - 0.01
  - - 0.0
    - 1.0
  x_for_ux: 0.5
training_data:
  condition:
    Re: 1.
    L: 1.
    ux_upper_wall: 1.
    random_arrange: False
    slide: 0.03
    use_gradp_training: False
    infer_gradp: False
    infer_ux_wall: False
  generate_params:
    div_num: 12
    div_pad: 0.03
    f_num: 12
    f_pad: 0.03
    p_num: 22
    u_num: 22
  num_training_points:
    divu: 144
    fx: 144
    fy: 144
    p: 22
    ux: 22
    uy: 22
test_data:
  test_num: 11
lbls:
  train:
  - 'r'
  - 'f'
  test:
  - 'r'
  - 'f'
  infer:
  - 'f'
  - 'std'
  record:
  - 'x'
  - 'fun'
  - 'norm_of_grads'
  analysis:
  - 'abs_error'
  - 'rel_error'
  - 'max_abs_error'
  - 'max_rel_error'
  - 'mean_abs_error'
  - 'mean_rel_error'
  kernel_arg:
  - 'uxux'
  - 'uyuy'
  - 'pp'
  - 'uxuy'
  - 'uxp'
  - 'uyp'
vnames:
  train:
  - 'ux'
  - 'uy'
  - 'p'
  - 'fx'
  - 'fy'
  - 'divu'
  test:
  - 'ux'
  - 'uy'
  - 'p'
  infer:
  - 'ux'
  - 'uy'
  - 'p'
  analysis:
  - 'ux'
  - 'uy'
  - 'p'
system_type: 'Stokes_2D'
