calc:
  epsilon: 1.0e-06
model:
  init_kernel_hyperparameter:
    - 0.0
    - 0.0
  kernel_form: product
  kernel_type: se
  distance_func: False
  num_mixture: 1
optimization:
  eps: 1.0e-05
  lr: 1.0e-02
  maxiter_GD: 400
  maxiter_scipy: 
  - 1
  method_GD: adam
  method_scipy: 
  - Nelder-Mead
  loss_ridge_regression: false
  print_process: true
plot:
  error_limit:
  - 0.0001
  - 0.1
  std_limit:
  - 0
  - 0.002
  val_limits:
  - - -1.0
    - 1.0
  x_for_ux: 0.5
test_data:
  test_num: 50
training_data:
  condition:
    use_pbc_points: False
  generate_params:
    y_num: 10
lbls:
  train:
  - 'r' 
  - 'f'
  test:
  - 'r'
  - 'f'
  infer:
  - 'f'
  - 'std'
  record:
  - x
  - fun
  - norm_of_grads
  analysis:
  - 'abs_error'
  - 'rel_error'
  - 'max_abs_error'
  - 'max_rel_error'
  - 'mean_abs_error'
  - 'mean_rel_error'
  kernel_arg:
  - 'yy'
vnames:
  train:
   - "y"
  test:
   - "y"
  infer:
   - "y"
  analysis:
   - "y"
system_type: '1D'
input_dim: 1
