model:
  add_noise: false
  init_kernel_hyperparameter:
    pp:
    - 0.4
    - -2.0
    - -2.0
    uxp:
    - 0.0
    - -2.0
    - -2.0
    uxux:
    - 0.4
    - -2.0
    - -2.0
    uxuy:
    - 0.0
    - -2.0
    - -2.0
    uyp:
    - 0.0
    - -2.0
    - -2.0
    uyuy:
    - 0.4
    - -2.0
    - -2.0
  kernel_form: product
  kernel_type: se
  distance_func: false
  epsilon: 1.0e-06
  input_dim: 2
  system_type: Stokes_2D
  index_optimize_noise: null
optimization:
  eps: 0.0001
  loss_ridge_regression: false
  lr: 1.0e-05
  maxiter_GD: 0
  maxiter_scipy: 
  - 500
  method_GD: adam
  method_scipy: 
  - Nelder-Mead
  print_process: True
  interval_check: null
  index_fixed: null
